### ISSUE TITLE
ImportError: No module named django.core.wsgi

### ISSUE THREAD

**Issue by miguelgfierro** [miguelgfierro/sciblog#110]
```
[Sat Feb 05 06:33:20.158084 2022] [wsgi:info] [pid 4874:tid 140690906498816] [remote 188.26.196.76:0] mod_wsgi (pid=4874, process='miguelgfierro.com', application=''): Loading WSGI script '/var/www/sciblog/sciblog/wsgi.py'.
[Sat Feb 05 06:33:20.158845 2022] [wsgi:error] [pid 4874:tid 140690906498816] [remote 188.26.196.76:0] mod_wsgi (pid=4874): Target WSGI script '/var/www/sciblog/sciblog/wsgi.py' cannot be loaded as Python module.
[Sat Feb 05 06:33:20.158855 2022] [wsgi:error] [pid 4874:tid 140690906498816] [remote 188.26.196.76:0] mod_wsgi (pid=4874): Exception occurred processing WSGI script '/var/www/sciblog/sciblog/wsgi.py'.
[Sat Feb 05 06:33:20.158881 2022] [wsgi:error] [pid 4874:tid 140690906498816] [remote 188.26.196.76:0] Traceback (most recent call last):
[Sat Feb 05 06:33:20.158907 2022] [wsgi:error] [pid 4874:tid 140690906498816] [remote 188.26.196.76:0]   File "/var/www/sciblog/sciblog/wsgi.py", line 11, in <module>
[Sat Feb 05 06:33:20.158973 2022] [wsgi:error] [pid 4874:tid 140690906498816] [remote 188.26.196.76:0]     from django.core.wsgi import get_wsgi_application
[Sat Feb 05 06:33:20.158996 2022] [wsgi:error] [pid 4874:tid 140690906498816] [remote 188.26.196.76:0] ImportError: No module named django.core.wsgi
[Sat Feb 05 06:33:20.913729 2022] [wsgi:info] [pid 4874:tid 140690839332608] [remote 188.26.196.76:65055] mod_wsgi (pid=4874, process='miguelgfierro.com', application=''): Loading WSGI script '/var/www/sciblog/sciblog/wsgi.py'.
[Sat Feb 05 06:33:20.914107 2022] [wsgi:error] [pid 4874:tid 140690839332608] [remote 188.26.196.76:65055] mod_wsgi (pid=4874): Target WSGI script '/var/www/sciblog/sciblog/wsgi.py' cannot be loaded as Python module.
[Sat Feb 05 06:33:20.914117 2022] [wsgi:error] [pid 4874:tid 140690839332608] [remote 188.26.196.76:65055] mod_wsgi (pid=4874): Exception occurred processing WSGI script '/var/www/sciblog/sciblog/wsgi.py'.
[Sat Feb 05 06:33:20.914150 2022] [wsgi:error] [pid 4874:tid 140690839332608] [remote 188.26.196.76:65055] Traceback (most recent call last):
[Sat Feb 05 06:33:20.914184 2022] [wsgi:error] [pid 4874:tid 140690839332608] [remote 188.26.196.76:65055]   File "/var/www/sciblog/sciblog/wsgi.py", line 11, in <module>
[Sat Feb 05 06:33:20.914220 2022] [wsgi:error] [pid 4874:tid 140690839332608] [remote 188.26.196.76:65055]     from django.core.wsgi import get_wsgi_application
[Sat Feb 05 06:33:20.914253 2022] [wsgi:error] [pid 4874:tid 140690839332608] [remote 188.26.196.76:65055] ImportError: No module named django.core.wsgi
[Sat Feb 05 06:34:03.977195 2022] [wsgi:info] [pid 4874:tid 140690906498816] [remote 198.199.108.231:65055] mod_wsgi (pid=4874, process='miguelgfierro.com', application=''): Loading WSGI script '/var/www/sciblog/sciblog/wsgi.py'.
[Sat Feb 05 06:34:03.977532 2022] [wsgi:error] [pid 4874:tid 140690906498816] [remote 198.199.108.231:65055] mod_wsgi (pid=4874): Target WSGI script '/var/www/sciblog/sciblog/wsgi.py' cannot be loaded as Python module.
[Sat Feb 05 06:34:03.977542 2022] [wsgi:error] [pid 4874:tid 140690906498816] [remote 198.199.108.231:65055] mod_wsgi (pid=4874): Exception occurred processing WSGI script '/var/www/sciblog/sciblog/wsgi.py'.
[Sat Feb 05 06:34:03.977562 2022] [wsgi:error] [pid 4874:tid 140690906498816] [remote 198.199.108.231:65055] Traceback (most recent call last):
[Sat Feb 05 06:34:03.977587 2022] [wsgi:error] [pid 4874:tid 140690906498816] [remote 198.199.108.231:65055]   File "/var/www/sciblog/sciblog/wsgi.py", line 11, in <module>
[Sat Feb 05 06:34:03.977628 2022] [wsgi:error] [pid 4874:tid 140690906498816] [remote 198.199.108.231:65055]     from django.core.wsgi import get_wsgi_application
[Sat Feb 05 06:34:03.977652 2022] [wsgi:error] [pid 4874:tid 140690906498816] [remote 198.199.108.231:65055] ImportError: No module named django.core.wsgi
```
related to #109

**Comment by miguelgfierro** [comment]
I had to create a new conda env with python 3.5, install the dependencies and change the WSGIDaemonProcess to:
```
WSGIDaemonProcess miguelgfierro.com python-path=/var/www/sciblog:/home/ubuntu/anaconda/envs/py35/lib/python3.5/site-packages
```
