### ISSUE TITLE
Error when adding pretty-embed.js to the blog

### ISSUE THREAD

**Issue by miguelgfierro** [miguelgfierro/sciblog#146]
In this PR #145, I'm trying to add pretty-emded.js: https://github.com/mike-zarandona/prettyembed.js

When adding pretty-embed.js to the blog like this:
```
        <div class="row">
            <div class="two columns">&nbsp;</div>
            <div class="twelve columns">
                <div id="pretty-youtube"></div>
            </div>
            <div class="two columns">&nbsp;</div>
        </div>

<script>
    (function ($) {
        $(document).ready(function () {
            $('#pretty-youtube').prettyEmbed({
                videoID: '{{ object.youtube_video_id }}',
                useFitVids: false,
                playerControls: false,
                playerInfo: false,
                //previewSize: 'hd', 
                // customPreviewImage: 'https://img.youtube.com/vi/{{ object.youtube_video_id }}/maxresdefault.jpg',
                customPreviewImage: 'https://img.youtube.com/vi/{{ object.youtube_video_id }}/0.jpg',
            });
        });
    })(jQuery);
</script>
```

I get the following error:
```
pretty-embed.js:3  
       Uncaught TypeError: t(...).on is not a function
    at t.fn.prettyEmbed (pretty-embed.js:3:10334)
    at HTMLDocument.<anonymous> ((index):414:34)
    at Object.resolveWith (jquery.min.js:8:18686)
    at Function.ready (jquery.min.js:8:12712)
    at HTMLDocument.B (jquery.min.js:8:18020)
```

However, in a complete clean page, the same code works: https://github.com/miguelgfierro/codebase/tree/main/js/web/borderless_youtube

**Comment by miguelgfierro** [comment]
Won't fix
