### ISSUE TITLE
Set up mobile view

### ISSUE THREAD

**Issue by miguelgfierro** [miguelgfierro/sciblog#84]
The current mobile view is not responsive, and it is loading the desktop version

**Comment by miguelgfierro** [comment]
system is not taking
```
class MobileTemplatesMiddleware(object):
    """Determines which set of templates to use for a mobile site"""

    ORIG_TEMPLATE_DIRS = settings.TEMPLATE_DIRS

    def process_request(self, request):
        is_mobile = False
        if request.META.has_key("HTTP_USER_AGENT"):
            user_agent = request.META["HTTP_USER_AGENT"]
            b = reg_b.search(user_agent)
            v = reg_v.search(user_agent[0:4])
            if b or v:
                is_mobile = True

        if is_mobile:
            settings.TEMPLATE_DIRS = (
                settings.MOBILE_TEMPLATE_DIRS + self.ORIG_TEMPLATE_DIRS
            )
        else:
            settings.TEMPLATE_DIRS = (
                settings.DESKTOP_TEMPLATE_DIRS + self.ORIG_TEMPLATE_DIRS
            )


```

**Comment by miguelgfierro** [comment]
in development, it works correctly, but then in the server it doesn't. If I look at `/var/log/apache2/error.log`, I get:

```
[Sun Mar 28 21:06:50.855986 2021] [wsgi:error] [pid 22153:tid 139740463159040] is_mobile? = True
```

**Comment by miguelgfierro** [comment]
tried getting the wsgi lines outside the virtual host, but didn't work

**Comment by miguelgfierro** [comment]
considerar https://django-debug-toolbar.readthedocs.io/en/latest/installation.html#configuring-internal-ips?

**Comment by miguelgfierro** [comment]
If I use the local configuration and connect with the mobile, it works. It might be related to a bad configuration of apache?

**Comment by miguelgfierro** [comment]
debug for error: `cat /var/log/apache2/sciblog.error.log` (the server has 1h less than London)
debug for access `cat /var/log/apache2/sciblog.access.log`

**Comment by miguelgfierro** [comment]
according to [this link](https://docs.quantifiedcode.com/python-anti-patterns/django/1.8/migration/template_dirs_deprecated.html), `TEMPLATE_DIRS` is deprecated. 

If I change the settings:
```
MOBILE_TEMPLATE_DIRS = os.path.join(BASE_DIR, "blog", "templates", "mobile")
DESKTOP_TEMPLATE_DIRS = os.path.join(BASE_DIR, "blog", "templates", "desktop")
CURRENT_TEMPLATE = DESKTOP_TEMPLATE_DIRS
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            # insert your TEMPLATE_DIRS here
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                # Insert your TEMPLATE_CONTEXT_PROCESSORS here or use this
                # list if you haven't customized them:
                "django.contrib.auth.context_processors.auth",
                "django.template.context_processors.debug",
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
            ],
        },
    },
]
```
and the change `middleware.py` to change when the request comes the DIRS:
```
def process_request(self, request):
        is_mobile = False
        if request.META.has_key("HTTP_USER_AGENT"):
            user_agent = request.META["HTTP_USER_AGENT"]
            b = reg_b.search(user_agent)
            v = reg_v.search(user_agent[0:4])
            if b or v:
                is_mobile = True
        print "is_mobile? =", is_mobile
        if is_mobile:
            settings.TEMPLATES[0]["DIRS"] = settings.MOBILE_TEMPLATE_DIRS
            # pass
        else:
            settings.TEMPLATES[0]["DIRS"] = settings.DESKTOP_TEMPLATE_DIRS
            # pass
        print settings.TEMPLATES
```

I get an error that it is not finding the template, however, `print  settings.TEMPLATES` outputs: 
```
[{'DIRS': 'C:\\run3x\\sciblog\\blog\\templates\\desktop', 'APP_DIRS': True, 'OPTIONS': {'context_processors': ['django.contrib.auth.context_processors.auth', 'django.template.context_processors.debug', 'django.template.context_processors.i18n', 'django.template.context_processors.media', 'django.template.context_processors.static']}, 'BACKEND': 'django.template.backends.django.DjangoTemplates'}]
Internal Server Error: /
Traceback (most recent call last):
  File "C:\instagramApi\Local\Continuum\anaconda3\envs\py27\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\miguel\Local\Continuum\anaconda3\envs\py27\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\miguel\Local\Continuum\anaconda3\envs\py27\lib\site-packages\django\template\response.py", line 133, in rendered_content
    template = self._resolve_template(self.template_name)
  File "C:\miguel\Local\Continuum\anaconda3\envs\py27\lib\site-packages\django\template\response.py", line 88, in _resolve_template
    new_template = self.resolve_template(template)
  File "C:\miguel\Local\Continuum\anaconda3\envs\py27\lib\site-packages\django\template\response.py", line 78, in resolve_template
    return loader.select_template(template, using=self.using)
  File "C:\miguel\Local\Continuum\anaconda3\envs\py27\lib\site-packages\django\template\loader.py", line 76, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list))
TemplateDoesNotExist: blog/post_list.html
[03/Apr/2021 23:38:10] "GET / HTTP/1.1" 500 96971
```

**Comment by miguelgfierro** [comment]
consider changing the view: https://stackoverflow.com/questions/35863800/mobile-templates-based-on-user-agent-in-django-ensuring-thread-safety

**Comment by miguelgfierro** [comment]
consider function based view: https://subscription.packtpub.com/book/web_development/9781784391911/1/ch01lvl1sec15/adding-pagination

**Comment by miguelgfierro** [comment]
when following [this](https://stackoverflow.com/questions/64993859/how-to-use-django-user-agents-with-class-listviews) to overwrite `get_template_names` I start seeing the right template. However, now in the detail view I can't see the content. When I enter a post I see: "There Are No Posts"
